title: Ioannis Demetriade's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ioannisdem.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Ioannis Demetriades # add your name
author-img: ioannis-demetriades.png # add your photo
about-author: I am a Data Scientist passionate about applying my skills to tackle real-world challenges. # add description
social-facebook: # add your Facebook handle
social-github: IoannisDem # add your Github handle
social-linkedin: ioannisdemetriades # add your Linkedin handle
social-email: ioannisdem2000@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
